Задание 1

In [2]:
import numpy as np

arr = np.arange(1, 10).reshape((3, 3))

arr *= 2

arr[arr > 10] = 0

print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


Задание 2

In [3]:
import numpy as np

array = np.random.randint(1, 101, size=20)

divisible_by_5 = array % 5 == 0

print("Элементы, делящиеся на 5:", array[divisible_by_5])

array[divisible_by_5] = -1

print("\nОбновленный массив:")
print(array)

Элементы, делящиеся на 5: [20 60 45]

Обновленный массив:
[16 22 39 11 56 41 -1 77 76 12 32 38 36 73 26 89  4 -1 -1 32]


Задание 3

In [4]:
import numpy as np

array1 = np.random.randint(0, 51, size=(1, 5))
array2 = np.random.randint(0, 51, size=(1, 5))

print("Массив 1:", array1)
print("Массив 2:", array2)

sum_array = array1 + array2 
diff_array = array1 - array2
prod_array = array1 * array2

print("\nСумма массивов:", sum_array)
print("Разность массивов:", diff_array)
print("Произведение массивов:", prod_array)

Массив 1: [[0 8 0 3 3]]
Массив 2: [[31  0 40 30 10]]

Сумма массивов: [[31  8 40 33 13]]
Разность массивов: [[-31   8 -40 -27  -7]]
Произведение массивов: [[ 0  0  0 90 30]]


Задание 4

In [5]:
import numpy as np

array = np.linspace(-10, 10, num=50)

total_sum = np.sum(array)                 
positive_sum = np.sum(array[array > 0])  
negative_sum = np.sum(array[array < 0])  

print(f"Общая сумма элементов: {total_sum}")
print(f"Сумма положительных элементов: {positive_sum}")
print(f"Сумма отрицательных элементов: {negative_sum}")

Общая сумма элементов: 7.105427357601002e-15
Сумма положительных элементов: 127.55102040816328
Сумма отрицательных элементов: -127.55102040816327


Задание 5

In [6]:
import numpy as np

unit_matrix = np.eye(4)

diag_matrix = np.diag([5, 10, 15, 20])

sum_unit = np.sum(unit_matrix)
sum_diag = np.sum(diag_matrix)

print("Единичная матрица 4x4:\n", unit_matrix)
print("Сумма элементов единичной матрицы:", sum_unit)

print("\nДиагональная матрица 4x4:\n", diag_matrix)
print("Сумма элементов диагональной матрицы:", sum_diag)

if sum_unit < sum_diag:
    print("Сумма элементов диагональной матрицы больше.")
elif sum_unit > sum_diag:
    print("Сумма элементов единичной матрицы больше.")
else:
    print("Суммы совпадают.")

Единичная матрица 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Сумма элементов единичной матрицы: 4.0

Диагональная матрица 4x4:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов диагональной матрицы: 50
Сумма элементов диагональной матрицы больше.


Задание 6

In [7]:
import numpy as np

matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

sum_matrix = matrix1 + matrix2           
diff_matrix = matrix1 - matrix2          
elementwise_product = matrix1 * matrix2  

print("Матрица 1:\n", matrix1)
print("Матрица 2:\n", matrix2)
print("Сумма матриц:\n", sum_matrix)
print("Разность матриц:\n", diff_matrix)
print("Поэлементное произведение матриц:\n", elementwise_product)

Матрица 1:
 [[ 8  5  9]
 [ 7  7 14]
 [ 6 10 12]]
Матрица 2:
 [[17  2  7]
 [18 11  9]
 [18 16 14]]
Сумма матриц:
 [[25  7 16]
 [25 18 23]
 [24 26 26]]
Разность матриц:
 [[ -9   3   2]
 [-11  -4   5]
 [-12  -6  -2]]
Поэлементное произведение матриц:
 [[136  10  63]
 [126  77 126]
 [108 160 168]]


Задание 7

In [8]:
import numpy as np

matrix_a = np.random.randint(1, 11, size=(2, 3))
matrix_b = np.random.randint(1, 11, size=(3, 2))

product_matrix = matrix_a @ matrix_b 

print("Матрица A (2x3):\n", matrix_a)
print("Матрица B (3x2):\n", matrix_b)
print("Произведение матриц AB:\n", product_matrix)

Матрица A (2x3):
 [[1 8 1]
 [5 4 8]]
Матрица B (3x2):
 [[7 7]
 [1 1]
 [7 1]]
Произведение матриц AB:
 [[22 16]
 [95 47]]


Задание 8

In [9]:
import numpy as np

random_matrix = np.random.randint(1, 21, size=(3, 3))

determinant = np.linalg.det(random_matrix)
inverse_matrix = None
if determinant != 0:
    inverse_matrix = np.linalg.inv(random_matrix)
else:
    print("Матрица вырожденная (определитель равен 0)")

print("Исходная матрица:\n", random_matrix)
print("Определитель матрицы:", determinant)
if inverse_matrix is not None:
    print("Обратная матрица:\n", inverse_matrix)

Исходная матрица:
 [[11  1 13]
 [ 7  4 14]
 [ 7 14  4]]
Определитель матрицы: -999.9999999999998
Обратная матрица:
 [[ 0.18  -0.178  0.038]
 [-0.07   0.047  0.063]
 [-0.07   0.147 -0.037]]


Задание 9

In [10]:
import numpy as np

matrix = np.random.randint(1, 51, size=(4, 4))

print("Исходная матрица:\n", matrix)

transposed_matrix = matrix.T 

print("\nТранспонированная матрица:\n", transposed_matrix)

trace_value = np.trace(matrix)

print("\nСлед матрицы (сумма элементов главной диагонали):", trace_value)

Исходная матрица:
 [[30 44 34 34]
 [35  6 15 20]
 [22 35 34 11]
 [ 3 25 34 29]]

Транспонированная матрица:
 [[30 35 22  3]
 [44  6 35 25]
 [34 15 34 34]
 [34 20 11 29]]

След матрицы (сумма элементов главной диагонали): 99


Задание 10

In [11]:
import numpy as np

A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

B = np.array([5, 6, -2])

solution = np.linalg.solve(A, B)

print("Решение системы уравнений:")
print(solution)

Решение системы уравнений:
[1.63963964 0.57657658 0.00900901]


Индивидуальное задание 
Вариант 3

In [12]:
import numpy as np

A = np.array([
    [1, 1, 1],
    [-1, 1, 0],
    [-1.5, 0, 1]
])

B = np.array([500, 50, 0])

det_A = np.linalg.det(A)
A_x = A.copy(); A_x[:, 0] = B
A_y = A.copy(); A_y[:, 1] = B
A_z = A.copy(); A_z[:, 2] = B
x_cramer = np.linalg.det(A_x) / det_A
y_cramer = np.linalg.det(A_y) / det_A
z_cramer = np.linalg.det(A_z) / det_A

inv_A = np.linalg.inv(A)
solution_inv = inv_A @ B

solution_numpy = np.linalg.solve(A, B)

print("Решение методом Крамера:", x_cramer, y_cramer, z_cramer)
print("Решение методом обратной матрицы:", solution_inv)
print("Решение с помощью np.linalg.solve:", solution_numpy)

Решение методом Крамера: 128.5714285714286 178.57142857142853 192.85714285714295
Решение методом обратной матрицы: [128.57142857 178.57142857 192.85714286]
Решение с помощью np.linalg.solve: [128.57142857 178.57142857 192.85714286]
